### ISSUE TITLE
tweak UI of buttons to that of material ui ones

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/translang#10]

**Comment by Daggerpov** [comment]
![image](https://user-images.githubusercontent.com/53918934/180620656-a3f80ef6-7dfa-4086-b13c-37d0b3bb7bf2.png)
![image](https://user-images.githubusercontent.com/53918934/180620661-800cb62d-c4de-42f8-a19a-815f7ae8962c.png)

**Comment by Daggerpov** [comment]
- [ ] "make another translation"

<img width="183" alt="image" src="https://user-images.githubusercontent.com/53918934/180663941-6e7493f9-496f-4463-b6ec-4c80f9a3fd18.png">

- [ ] "Submit for validation"/"Submitted"

keep in mind the text changes in this one
<img width="167" alt="image" src="https://user-images.githubusercontent.com/53918934/180663944-8b508ff8-12c8-4069-9368-7511415590c0.png">

**Comment by Daggerpov** [comment]
- [ ] same fix to this one as the selectors in `index.tsx` needs to be done:
<img width="228" alt="image" src="https://user-images.githubusercontent.com/53918934/180664116-b6360574-5a75-49bd-a0b4-a50bbfd20111.png">

**Comment by DaoTimothy** [comment]
Also updated the "Copy to Clipboard" and "Submit a Complaint" buttons on index page
