### ISSUE TITLE
Change Rating Icon Styling

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/translang#11]
This rating selector currently works through database entries, with its value now being able to be read:

![image](https://user-images.githubusercontent.com/53918934/180661714-d86cd789-754c-4695-8a1d-8d6687aa1844.png)

However, I'd simply like the style to be changed from stars to another icon that's more suited for "urgency" rather than the default:

![image](https://user-images.githubusercontent.com/53918934/180661740-02016f04-070c-4303-9549-636117f7f9ab.png)

## Replace the Rating tag with the commented StyledRating one

![image](https://user-images.githubusercontent.com/53918934/180661800-fe2d976c-0a0d-444a-bbca-e13a1d2549c5.png)

## Using this code as a reference (taken from [this website's](https://mui.com/material-ui/react-rating/) "customization" section), change it from hearts to another icon:

![image](https://user-images.githubusercontent.com/53918934/180661794-a59dbc01-023d-462f-b3dd-c4ab1ee440b2.png)

## Perhaps something similar to this idea could be implemented, with varying icons for each rating setting (this is found in the "Radio group" section of that same aforementioned website):

![image](https://user-images.githubusercontent.com/53918934/180661931-2dfaa048-59f7-49d2-9663-20f0fbe466e9.png)

**Comment by DaoTimothy** [comment]
https://mui.com/material-ui/material-icons/?query=excl&selected=PriorityHigh
going to use these icons, better for showing priority level

**Comment by Daggerpov** [comment]
currently, the icon suffices but maybe it'd be cooler in the future to have varying looks such as what's in the last screenshot of the original message above

**Comment by Daggerpov** [comment]
https://mui.com/material-ui/react-rating/
https://mui.com/material-ui/material-icons/?query=priority

**Comment by Daggerpov** [comment]
we can come back to this but it's no longer a pressing issue.
