### ISSUE TITLE
Menu Display Name and Image

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/translang#13]
- [ ] put display name next to profile picture
- [ ] fix profile picture not displaying ([I've asked this StackOverflow question](https://stackoverflow.com/questions/73113400/react-accessing-photourl-from-firebase-user-image-not-displaying))

**Comment by Daggerpov** [comment]
![image](https://user-images.githubusercontent.com/53918934/181720399-1218dd44-a1b6-4257-a049-bbde92162ca2.png)

The only thing is now to change the `<IconButton>` to a more fitting shape than this oval (probably a basic rectangle to contain the name and profile image in the button). @DaoTimothy

**Comment by DaoTimothy** [comment]
Changed IconButton to Button to make the shape a rectangle.
![image](https://user-images.githubusercontent.com/79426229/181876478-177eb366-397e-4e00-af6c-7d08f048447a.png)
![image](https://user-images.githubusercontent.com/79426229/181876485-86114b6a-51c6-41c3-ac2c-6a8610e9823b.png)
