### ISSUE TITLE
Database Entry Additions / Submit Complaint Changes

### ISSUE THREAD

**Issue by Daggerpov** [Daggerpov/translang#17]
Fields that we need to get working with mongoDB are:

- [x] a "faulty lines" list to correspond with this selector:

![image](https://user-images.githubusercontent.com/53918934/181877469-913e21cc-5f1f-4296-9626-3fbe5b2dafd5.png)

- [x] in the opposite manner, since there is a title field in the mongoDB, we need to make a feature within our app to type one to go along with the complaint submission which would be near the top of all this (this is easy so @DaoTimothy can do this):

![image](https://user-images.githubusercontent.com/53918934/181877505-b60e293f-0544-4591-9d60-aa10222742fe.png)

**Comment by DaoTimothy** [comment]
Added form for title on complaint page, no functionality as of yet though

**Comment by Daggerpov** [comment]
made title and faulty lines get submitted to mongoDB as such:

![Uploading image.png…]()
